"""add notes table

Revision ID: 679b552f83a2
Revises: ad24eec47ad2
Create Date: 2025-09-01 21:38:34.035879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679b552f83a2'
down_revision: Union[str, None] = 'ad24eec47ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('notes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('notes', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.drop_index('ix_notes_id', table_name='notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_notes_id', 'notes', ['id'], unique=False)
    op.alter_column('notes', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('notes', 'updated_at')
    op.drop_column('notes', 'created_at')
    # ### end Alembic commands ###
